# Generated by Django 3.1.7 on 2021-02-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210226_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
